### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use object of type WP_Post 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#21]
I just updated Rest Easy, and now I get this fatal error.

```
Fatal error: Uncaught Error: Cannot use object of type WP_Post as array in /app/public/wp-content/plugins/rest-easy/serializers/related.php:19
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(286): rez_default_gather_related(Object(WP_Post))
#1 /app/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Object(WP_Post), Array)
#2 /app/public/wp-content/themes/bernards2018/functions/rest-easy-filters.php(183): apply_filters('rez_gather_rela...', Object(WP_Post))
#3 /app/public/wp-includes/class-wp-hook.php(286): serialize_home_pages(Array)
#4 /app/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#5 /app/public/wp-content/plugins/rest-easy/builders.php(39): apply_filters('rez_build_site_...', Array)
#6 /app/public/wp-content/plugins/rest-easy/builders.php(11): rez_build_site_data()
#7 /app/public/wp-content/plugins/rest-easy/rest-easy.php(58): rez_build_all_data()
#8 /app/public/wp-includes/class-wp-hook.php(286): rez_localize_data('')
#9 /app/public/wp-includes/class-wp-hook.php(310): W in /app/public/wp-content/plugins/rest-easy/serializers/related.php on line 19
```

**Comment by drewbaker** [comment]
Actually seems to be related to a filter I've written, so I'll see if I can fix it in my theme.

**Comment by jrobson153** [comment]
try what I posted in this thread: https://github.com/funkhaus/Rest-Easy/issues/20
